### PR TITLE
Support react navigation v5

### PR DESCRIPTION
**Pull request by nandorojo**
To use:

```
yarn add expo-next-react-navigation@v5
```

### CODE REVIEW

**Comment by xiCO2k** [comment]
@nandorojo Hey Fernando, did notice for v5 <Link> only supports <Text> do you think you will add it in this pull request?

Thanks

**Comment by nandorojo** [comment]
Hey @xiCO2k! Could you clarify your question?

v5 is currently supported, by installing with `yarn add expo-next-react-navigation@v5`.

**Comment by xiCO2k** [comment]
Sorry @nandorojo so with the v5:

So on the components/links/index.tsx :
image

The LinkMaker from the expo-navigation-core only accepts Text.

You can check here:
image

Thanks for the quick response.

**Comment by nandorojo** [comment]
Ah got it, we can discuss on issue #13

**Comment by xiCO2k** [comment]
Hey @nandorojo one thing I notice, for web with the `isText={false}` prop, if the child does not have the accessibilityRole='link' prop it will render a <div> instead of an <a>. should be no big deal but just to let you guys know.

Thanks

**Comment by nandorojo** [comment]
Could you raise this on #13?

**Comment by kenberkeley** [comment]
Any update?

**Comment by nandorojo** [comment]
@kennerkeley update on what? You can use this with the @v5 tag

**Comment by kenberkeley** [comment]
@nandorojo I mean, is the example working in React Navigation v5?

https://github.com/nandorojo/expo-next-react-navigation/blob/e915879bf61b820666351c3cc370664ba5e827f3/examples/next-nav/package.json#L26-L27

**Comment by kenberkeley** [comment]
Gotcha! You are talking about https://github.com/nandorojo/expo-next-react-navigation/tree/v5/examples/react-navigation-5 !

**Comment by kenberkeley** [comment]
But there are no `createStackNavigator` set up code in `v5` branch, right?

**Pull request merged**
