### PR TITLE
use universal module scripts

### PR DESCRIPTION
**Pull request by EvanBacon**
## How

- remove yarn-error file
- remove generated files from `src` folder
- js code block -> sh
- use `expo-module-scripts`: The Expo SDK uses a unified set of tools for universal packages to ensure that the package is using the right versions of TypeScript, eslint, jest, babel, across web, ios, android, etc...
- Add Enzyme tests to web Link component
- Remove extra dependencies on compiler tools

## Test Plan

- run `yarn test` to run unit tests. Pressing `X` will let you isolate the platforms to just test web.

### CODE REVIEW

**Comment by nandorojo** [comment]
Thanks so much for the PR! Everything looks good – this is very helpful. I wasn't familiar with `expo-module-scripts`. 

The only issue I'm having is running the example app with `expo start --ios`.

These are the steps I took:
```sh
git clone https://github.com/EvanBacon/expo-next-react-navigation.git
cd expo-next-react-navigation
git checkout -b EvanBacon-@evanbacon/use-module-scripts master
git pull https://github.com/EvanBacon/expo-next-react-navigation.git @evanbacon/use-module-scripts
yarn

cd examples/next-nav
yarn
expo start --ios
```

Error:

```sh
  • Scan the QR code above with the Expo app (Android) or the Camera app (iOS).
  • Press a for Android emulator, or i for iOS simulator.
  • Press e to send a link to your phone with email.

 Expo  Press ? to show a list of all available commands.
Logs for your project will appear below. Press Ctrl+C to exit.
Error: Can't get version of package.
    at Object.getPublishInfoAsync (/@expo/xdl@57.2.1/src/Exp.ts:250:11)
    at manifestHandler (/@expo/xdl@57.2.1/src/Project.ts:1966:31)
```

Meanwhile, `yarn next dev` is working normally.

Let me know if I messed something up there, thanks again!

**Comment by EvanBacon** [comment]
will investigate further. Looks like two versions of webpack are being installed.

**Comment by nandorojo** [comment]
Sounds good, thanks!

**Comment by EvanBacon** [comment]
Can confirm that this works on iOS with the latest expo CLI. You may want to try again on your side as I couldn't repro the exact issue you reported. Also you should try running `npm pack` in the root folder then running `yarn add ../../expo-next-react-navigation-0.0.18.tgz` in the example folder. This will ensure that the example is running what would be the latest version of the code if it were published.

**Comment by nandorojo** [comment]
Got it, updating the cli fixed it for me. Also, thanks for the tip on `npm pack`! Everything looks good here, published to `0.0.20`.

**Pull request merged**
