### PR TITLE
Upgrade react & react-dom

### PR DESCRIPTION
**Pull request by emroot**
Upgrade react & react-dom

### CODE REVIEW

**Comment by nandorojo** [comment]
Looks good, I'll test this tomorrow and merge. Thanks for the PR!

**Comment by nandorojo** [comment]
Is updating react and react dom what fixes your bug in #10? Would #12 fix this?

**Comment by emroot** [comment]
nah, it was because i was using next 9.2, using 9.1.5 works like a charm. 
lemme try the new version. 
Feel free to close this PR, tho wouldn't hurt to upgrade react

**Comment by emroot** [comment]
new version works like a charm. thanks!

**Comment by nandorojo** [comment]
I’m going to close for now this since @expo’s latest SDK (36) uses react 16.9. I’ll re-open and merge once SDK 37 comes out.  

Thanks so much for the PR! Really appreciate you taking the time.

**Pull request closed without merging**
