### PR TITLE
Updated next

### PR DESCRIPTION
**Pull request by cmaycumber**
Fixes shallow routing by upgrading next to v10

### CODE REVIEW

**Comment by nandorojo** [comment]
Should we upgrade RN while we're at it?

**Comment by nandorojo** [comment]
Maybe in a separate PR

**Comment by cmaycumber** [comment]
> Should we upgrade RN while we're at it?
> 
> This would require a PR to expo-navigation-core (should have been a monorepo 😬)

The react native is old, I'm on expo 41, I assume you probably are too. I can help with this too if it's something you think we should do.

**Comment by cmaycumber** [comment]
> expo-navigation-core

Can we monorepo it?

**Comment by nandorojo** [comment]
Oh sorry I meant React navigation. I'm not sure if the RN dev dependency makes a difference, I don't think it does.

**Comment by cmaycumber** [comment]
That's a good point. It probably won't have an impact

**Comment by nandorojo** [comment]
I really would like to get types working for React navigation with `useRouting` but I never spent much time on it

**Comment by cmaycumber** [comment]
> I really would like to get types working for React navigation with `useRouting` but I never spent much time on it

Do you think it's possible? I'll see if I can take a jab at it sometime this week.

**Comment by nandorojo** [comment]
Yeah I think so. I started it before. I think it just needs some tweaks. 

For instance, if we pass the navigation prop type as the first generic, we might need to then extract its arguments for `useRouting`

I did something similar for the next web stack I'm slowly working on

**Pull request merged**
